/// Generated by AssetsRefGenerator on 2020/08/31
class Res {
  static const String lato_black = "assets/fonts/lato_black.ttf";
  static const String lato_bold = "assets/fonts/lato_bold.ttf";
  static const String lato_light = "assets/fonts/lato_light.ttf";
  static const String lato_regular = "assets/fonts/lato_regular.ttf";
  static const String LatoRegular = "assets/fonts/LatoRegular.otf";
  static const String ic_circular_apple = "assets/images/icons/ic_circular_apple.png";
  static const String ic_circular_fb = "assets/images/icons/ic_circular_fb.png";
  static const String ic_circular_google = "assets/images/icons/ic_circular_google.png";
}
